name: Keep Render Alive

on:
  schedule:
    - cron: "*/13 * * * *"  # Every 13 minutes

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render App
        run: curl -s https://client-magnet.onrender.com/
