name: update-site-list

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Generate site-list.html
        run: node scripts/generate-site-list.cjs

      - name: Debug generated list
        run: cat site-list.html

      - name: Commit and push changes
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add site-list.html
          git commit -m "Update site-list.html index" || echo "No changes to commit"
          git push https://x-access-token:$GH_PAT@github.com/${{ github.repository }}.git HEAD:main
