name: update-sitemap

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install xml2js

      - name: Run sitemap update script
        run: node scripts/update-sitemap.cjs

      - name: Run site-list generator
        run: node scripts/generate-site-list.cjs

      - name: Debug output files
        run: |
          cat sitemap.xml
          cat site-list.html

      - name: Commit and push changes
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git remote set-url origin https://x-access-token:$GH_PAT@github.com/${{ github.repository }}.git
          git add sitemap.xml site-list.html
          git commit -m "Update sitemap.xml and site-list.html via GitHub Actions" || echo "No changes to commit"
          git push origin HEAD:main
